### ISSUE TITLE
ModuleNotFoundError: No module named 'smsfly'

### ISSUE THREAD

**Issue by ghostku** [wk-tech/python-smsfly#14]
What am I doing wrong? The same error with Windows 10 and with Ubuntu

    C:\Users\ghost
    λ python --version
    Python 3.7.1

    C:\Users\ghost
    λ python -m pip freeze | grep 'SMS'
    SMSFly==0.1.5

    C:\Users\ghost
    λ python
    Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from smsfly import SMSFlyAPI
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'smsfly'
    >>>`

**Comment by ghostku** [comment]
It looks like there are node code in PyPI package :(

**Comment by ghostku** [comment]
#15

**Comment by webknjaz** [comment]
@ghostku here you go https://pypi.org/project/SMSFly/0.1.6/
